### ISSUE TITLE
Build error when building hamza-client

### ISSUE THREAD

**Issue by jrkosinski** [loadpipe/Hamza-medusa#5]
## Steps to reproduce: 
- cd /hamza-client 
-  run "yarn build" 

## Expected result: 
Builds with no error 

## Observed result: 

$ next build
next.config.js {}
   ▲ Next.js 14.1.3
   - Environments: .env.local

   Creating an optimized production build ...
next.config.js {}
Failed to compile.

4242.js from Terser
  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8690:1]
 8690 |         }),
 8691 |         handler: handlerP(getCommandHandler(`seed`, (args, cmd) => {
 8692 |             var _a;
 8693 |             (_a = process.env).NODE_ENV ?? ("production" = `development`);
      :                                             ^^^^^^^^^^^^
 8694 |             return cmd(args);
 8695 |         })),
 8696 |     })
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8704:1]
 8704 |             },
 8705 |         },
 8706 |         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 8707 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8708 |             return cmd(args);
 8709 |         })),
 8710 |     })
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8725:1]
 8725 |                 : `Set port. Defaults to ${defaultPort}`,
 8726 |         }),
 8727 |         handler: handlerP(getCommandHandler(`develop`, (args, cmd) => {
 8728 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8729 |             cmd(args);
 8730 |             // Return an empty promise to prevent handlerP from exiting early.
 8731 |             // The development server shouldn't ever exit until the user directly
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8750:1]
 8750 |                 : `Set port. Defaults to ${defaultPort}`,
 8751 |         }),
 8752 |         handler: handlerP(getCommandHandler(`start`, (args, cmd) => {
 8753 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8754 |             cmd(args);
 8755 |             // Return an empty promise to prevent handlerP from exiting early.
 8756 |             // The development server shouldn't ever exit until the user directly
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8782:1]
 8782 |             describe: "Set number of cpus to use. Defaults to max number of cpus available on the system (set by env.CPUS)",
 8783 |         }),
 8784 |         handler: handlerP(getCommandHandler(`start-cluster`, (args, cmd) => {
 8785 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8786 |             cmd(args);
 8787 |             // Return an empty promise to prevent handlerP from exiting early.
 8788 |             // The development server shouldn't ever exit until the user directly
      `----

Caused by:
    0: failed to parse input file
    1: Syntax Error
Error: 
  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8690:1]
 8690 |         }),
 8691 |         handler: handlerP(getCommandHandler(`seed`, (args, cmd) => {
 8692 |             var _a;
 8693 |             (_a = process.env).NODE_ENV ?? ("production" = `development`);
      :                                             ^^^^^^^^^^^^
 8694 |             return cmd(args);
 8695 |         })),
 8696 |     })
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8704:1]
 8704 |             },
 8705 |         },
 8706 |         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 8707 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8708 |             return cmd(args);
 8709 |         })),
 8710 |     })
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8725:1]
 8725 |                 : `Set port. Defaults to ${defaultPort}`,
 8726 |         }),
 8727 |         handler: handlerP(getCommandHandler(`develop`, (args, cmd) => {
 8728 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8729 |             cmd(args);
 8730 |             // Return an empty promise to prevent handlerP from exiting early.
 8731 |             // The development server shouldn't ever exit until the user directly
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8750:1]
 8750 |                 : `Set port. Defaults to ${defaultPort}`,
 8751 |         }),
 8752 |         handler: handlerP(getCommandHandler(`start`, (args, cmd) => {
 8753 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8754 |             cmd(args);
 8755 |             // Return an empty promise to prevent handlerP from exiting early.
 8756 |             // The development server shouldn't ever exit until the user directly
      `----

  x The left-hand side of an assignment expression must be a variable or a property access.
      ,-[8782:1]
 8782 |             describe: "Set number of cpus to use. Defaults to max number of cpus available on the system (set by env.CPUS)",
 8783 |         }),
 8784 |         handler: handlerP(getCommandHandler(`start-cluster`, (args, cmd) => {
 8785 |             "production" = "production" || 0;
      :             ^^^^^^^^^^^^
 8786 |             cmd(args);
 8787 |             // Return an empty promise to prevent handlerP from exiting early.
 8788 |             // The development server shouldn't ever exit until the user directly
      `----

Caused by:
    0: failed to parse input file
    1: Syntax Error

6058.js from Terser
  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116623:1]
 116623 |         }),
 116624 |         handler: handlerP(getCommandHandler(`seed`, (args, cmd) => {
 116625 |             var _a;
 116626 |             (_a = process.env).NODE_ENV ?? ("production" = `development`);
        :                                             ^^^^^^^^^^^^
 116627 |             return cmd(args);
 116628 |         })),
 116629 |     })
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116637:1]
 116637 |             },
 116638 |         },
 116639 |         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 116640 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116641 |             return cmd(args);
 116642 |         })),
 116643 |     })
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116658:1]
 116658 |                 : `Set port. Defaults to ${defaultPort}`,
 116659 |         }),
 116660 |         handler: handlerP(getCommandHandler(`develop`, (args, cmd) => {
 116661 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116662 |             cmd(args);
 116663 |             // Return an empty promise to prevent handlerP from exiting early.
 116664 |             // The development server shouldn't ever exit until the user directly
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116683:1]
 116683 |                 : `Set port. Defaults to ${defaultPort}`,
 116684 |         }),
 116685 |         handler: handlerP(getCommandHandler(`start`, (args, cmd) => {
 116686 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116687 |             cmd(args);
 116688 |             // Return an empty promise to prevent handlerP from exiting early.
 116689 |             // The development server shouldn't ever exit until the user directly
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116715:1]
 116715 |             describe: "Set number of cpus to use. Defaults to max number of cpus available on the system (set by env.CPUS)",
 116716 |         }),
 116717 |         handler: handlerP(getCommandHandler(`start-cluster`, (args, cmd) => {
 116718 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116719 |             cmd(args);
 116720 |             // Return an empty promise to prevent handlerP from exiting early.
 116721 |             // The development server shouldn't ever exit until the user directly
        `----

Caused by:
    0: failed to parse input file
    1: Syntax Error
Error: 
  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116623:1]
 116623 |         }),
 116624 |         handler: handlerP(getCommandHandler(`seed`, (args, cmd) => {
 116625 |             var _a;
 116626 |             (_a = process.env).NODE_ENV ?? ("production" = `development`);
        :                                             ^^^^^^^^^^^^
 116627 |             return cmd(args);
 116628 |         })),
 116629 |     })
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116637:1]
 116637 |             },
 116638 |         },
 116639 |         handler: handlerP(getCommandHandler(`migrate`, (args, cmd) => {
 116640 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116641 |             return cmd(args);
 116642 |         })),
 116643 |     })
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116658:1]
 116658 |                 : `Set port. Defaults to ${defaultPort}`,
 116659 |         }),
 116660 |         handler: handlerP(getCommandHandler(`develop`, (args, cmd) => {
 116661 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116662 |             cmd(args);
 116663 |             // Return an empty promise to prevent handlerP from exiting early.
 116664 |             // The development server shouldn't ever exit until the user directly
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116683:1]
 116683 |                 : `Set port. Defaults to ${defaultPort}`,
 116684 |         }),
 116685 |         handler: handlerP(getCommandHandler(`start`, (args, cmd) => {
 116686 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116687 |             cmd(args);
 116688 |             // Return an empty promise to prevent handlerP from exiting early.
 116689 |             // The development server shouldn't ever exit until the user directly
        `----

  x The left-hand side of an assignment expression must be a variable or a property access.
        ,-[116715:1]
 116715 |             describe: "Set number of cpus to use. Defaults to max number of cpus available on the system (set by env.CPUS)",
 116716 |         }),
 116717 |         handler: handlerP(getCommandHandler(`start-cluster`, (args, cmd) => {
 116718 |             "production" = "production" || 0;
        :             ^^^^^^^^^^^^
 116719 |             cmd(args);
 116720 |             // Return an empty promise to prevent handlerP from exiting early.
 116721 |             // The development server shouldn't ever exit until the user directly
        `----

Caused by:
    0: failed to parse input file
    1: Syntax Error

**Comment by german-bortoli** [comment]
I was also digging into this and found something interesting into the file `/node_modules/@medusajs/medusa-cli/dist/create-cli.js` this is assigning process.env.NODE_ENV some value, which I think this should not occur.

Probably it might be useful to investigate this further more.

**Comment by Garabed96** [comment]
I was able to resolve this issue by adding the following to the storefront env file
`NEXT_PUBLIC_NODE_ENV===development`
